# Generated by Django 3.0.5 on 2024-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Wellness Center', 'Wellness Center')], default='Wellness Center', max_length=50),
        ),
    ]
